name: Generate release artefact

on: [push]

jobs:
  build_release:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "^1.17"

      - name: Install tools
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          source: "github"
          kustomize: "latest"
          operator-sdk: "latest"
          ko: "latest"

      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Test build
        run: make test

      - name: Build container
        env:
          IMAGE_TAG_BASE: ${{ secrets.REGISTRY_USERNAME }}/${{ github.repository }}
        run: make docker-build docker-push
